### ISSUE TITLE
Add working e2e tests

### ISSUE THREAD

**Issue by vaikas** [knative-sandbox/eventing-camel#3]
**Describe the bug**
In order to run e2e tests for camel, we need to install some software looks like. We should add them, and also add an automagic release.

https://github.com/knative/test-infra/blob/master/guides/release_setup.md#setting-up-automated-releases

 **Expected behavior**

 **To Reproduce**
Launch the controller, it fails to start with:
E0915 22:33:42.994066       1 reflector.go:153] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:105: Failed to list *v1.Integration: the server could not find the requested resource (get integrations.camel.apache.org)

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by vaikas** [comment]
@nicolaferraro would you mind tackling this?

**Comment by nicolaferraro** [comment]
Sure.

**Comment by vaikas** [comment]
I think it might be interesting to see if we can make this work with kind?
We've been doing this in eventing-rabbitmq
https://github.com/knative-sandbox/eventing-rabbitmq/blob/master/.github/workflows/kind-e2e.yaml

**Comment by nicolaferraro** [comment]
We also have Kind based e2e tests in the Camel K repo, so it should be totally feasible
