### ISSUE TITLE
Deprecated CustomResourceDefinition

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-camel#39]
**Describe the bug**

Installing gives warnings, like:
```
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

 **Expected behavior**

Usage of `v1`

 **Knative release version**
0.19+

**Comment by nicolaferraro** [comment]
Closing this as per https://github.com/knative-sandbox/eventing-camel/pull/97.
