### ISSUE TITLE
Deprecated CRD_beta1 API is used

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-camel#57]
**Describe the bug**
use of deprecated API:
* https://github.com/knative-sandbox/eventing-camel/blob/master/config/300-camelsource.yaml#L15

**Expected behavior**
use of `v1`

**Knative release version**
all

**Additional context**
Starting w/ k8s 1.22 the `v1beta1` of the CRD API is no longer around

**Comment by nicolaferraro** [comment]
Closing this as per https://github.com/knative-sandbox/eventing-camel/pull/97.
